### ISSUE TITLE
Problem when call function find() many times in a controller.

### ISSUE THREAD

**Issue by hoangdd** [marianofino/Facebook-Plugin-for-CakePHP#3]
In my controller, i want to get all albums and all photo in each album. My code is:

```
$albums = $this->FacebookAlbum->find('all', array(
    'fields' => array('FacebookAlbum.name', 'FacebookAlbum.link'),
    'conditions' => array(
        'FacebookAlbum.owner' => $this->Auth->User('uid'))
    )
);
foreach ($albums as $album) {
    # code...
    $photos = $this->FacebookPhoto->find('all', array(
        'fields' => array('FacebookPhoto.link'),
        'conditions' => array(
            'FacebookPhoto.aid' => $album['FacebookAlbum']['aid'],
        )
    ));
    debug($photos);
}
```

```
array(
    (int) 0 => array(
        'FacebookAlbum' => array(
            ...
        )
    ),

    (int) 1 => array(
        'FacebookAlbum' => array(
            ...
        )
    ),

    ...

    (int) 20 => array(
        'FacebookPhoto' => array(
            ...
        )
    (int) 21 => array(
        'FacebookPhoto' => array(
            ...
        )
    )
    ...
)
```

In array result, has both FacebookAlbum and FacebookPhoto.
I try free variable at line 185 , FQL.php and problem is solved.

```
$ret = $this->getResults($this->classes);
unset($this->classes);
return $ret;
```

**Comment by evolvertech** [comment]
Hello, i have implemented this plugin in my cakephp project. When i click on the login button, then it successfully redirects to the Facebook page but when it loads back to my webpage, then it displays the error i.e.

Facebook API error code 12 (OAuthException): (#12) fql is deprecated for versions v2.1 and higher

Error: An Internal Error Has Occurred.

My cakephp version is 2.6.10
please help me in resolving my problem. Thanks a lot..!!
